import type { City } from './types'

export const cities: City[] = [
  // Tier 1
  {
    slug: 'sydney',
    name: 'Sydney',
    state: 'NSW',
    tier: 1,
    keywords: ['tech hub', 'startup ecosystem', 'fintech', 'enterprise software'],
    localDetails: `Startup ecosystem: 2,500+ tech startups, largest in Australia. Key hubs: Tech Central (Central-Eveleigh), Barangaroo, North Sydney. Dominant industries: Fintech, SaaS, professional services, property tech. Local accelerators: Startmate, Antler, Stone & Chalk. Business culture: Fast-moving, competitive, high expectations. ~40% of Australia's tech investment flows here.`,
  },
  {
    slug: 'melbourne',
    name: 'Melbourne',
    state: 'VIC',
    tier: 1,
    keywords: ['creative tech', 'SaaS companies', 'digital innovation', 'startup capital'],
    localDetails: `Startup ecosystem: 2,000+ startups, strong creative/design focus. Key hubs: Cremorne (tech precinct), Collingwood, CBD. Dominant industries: Retail tech, health tech, creative industries, hospitality. Local accelerators: LaunchVic programs, Melbourne Accelerator Program. Business culture: Design-conscious, relationship-focused. Australia's largest concentration of health tech startups.`,
  },
  {
    slug: 'brisbane',
    name: 'Brisbane',
    state: 'QLD',
    tier: 1,
    keywords: ['emerging tech', 'mining tech', 'government digital', 'growing startup scene'],
    localDetails: `Growing tech scene: $1B+ annual tech investment. Key industries: Construction tech, property, mining services, tourism. Major infrastructure boom (Olympics 2032). Business culture: Practical, less formal than Sydney/Melbourne. Fastest-growing capital city in Australia.`,
  },
  {
    slug: 'perth',
    name: 'Perth',
    state: 'WA',
    tier: 1,
    keywords: ['resources tech', 'mining software', 'FIFO workforce', 'energy sector'],
    localDetails: `Economy: Mining and resources capital, $170B+ export industry. Key industries: Mining tech, construction, engineering services, agriculture. Business challenges: Legacy systems, remote workforce management, compliance. Business culture: Practical, results-focused, less hype than east coast. 2-3 hour time difference from eastern states. Hard to find developers who understand resources sector.`,
  },
  {
    slug: 'adelaide',
    name: 'Adelaide',
    state: 'SA',
    tier: 1,
    keywords: ['defence tech', 'space industry', 'health tech', 'wine tech'],
    localDetails: `Key industries: Defence ($90B shipbuilding program), health, wine, manufacturing. Growing tech: Lot Fourteen innovation precinct, Australian Space Agency HQ. Business culture: Relationship-driven, lower cost base than east coast. Australia's defence capital. 30-40% lower operating costs than Sydney.`,
  },
  // Tier 2
  {
    slug: 'gold-coast',
    name: 'Gold Coast',
    state: 'QLD',
    tier: 2,
    keywords: ['tourism tech', 'hospitality software', 'property tech'],
    localDetails: `Industries: Tourism ($5B+), property development, health & wellness, marine. Business challenges: Seasonal fluctuations, booking/scheduling systems. Culture: Lifestyle-focused, small business heavy. Australia's 6th largest city, massive short-term rental market.`,
  },
  {
    slug: 'canberra',
    name: 'Canberra',
    state: 'ACT',
    tier: 2,
    keywords: ['government tech', 'defence software', 'cybersecurity'],
    localDetails: `Economy: 75% government-related. Key industries: Defence contractors, policy/research, associations, education. Business challenges: Government procurement, compliance, security clearances. Highest average income in Australia, very stable economy.`,
  },
  {
    slug: 'newcastle',
    name: 'Newcastle',
    state: 'NSW',
    tier: 2,
    keywords: ['industrial tech', 'port logistics', 'renewable energy'],
    localDetails: `Transition: From coal/steel to diversified economy. Key industries: Mining services, healthcare, university/education, renewable energy. Business culture: Working class roots, practical approach. Major hub for Hunter Valley region businesses.`,
  },
  {
    slug: 'wollongong',
    name: 'Wollongong',
    state: 'NSW',
    tier: 2,
    keywords: ['university tech', 'manufacturing software', 'regional innovation'],
    localDetails: `Key industries: Manufacturing, university research, steel/mining heritage, healthcare. Growing tech presence through University of Wollongong partnerships. Third largest city in NSW. Strong regional business community.`,
  },
  {
    slug: 'hobart',
    name: 'Hobart',
    state: 'TAS',
    tier: 2,
    keywords: ['tourism tech', 'agriculture software', 'Antarctic research'],
    localDetails: `Key industries: Tourism, agriculture, Antarctic research, creative industries. Business culture: Small community, relationships matter, boutique focus. Smallest capital but fastest growing property market. Limited local tech talent, remote work essential.`,
  },
  {
    slug: 'geelong',
    name: 'Geelong',
    state: 'VIC',
    tier: 2,
    keywords: ['manufacturing tech', 'regional growth', 'health services'],
    localDetails: `Manufacturing transition, major health precinct, commuter city to Melbourne. Growing independent business community. Strong focus on regional innovation and diversification.`,
  },
  {
    slug: 'sunshine-coast',
    name: 'Sunshine Coast',
    state: 'QLD',
    tier: 2,
    keywords: ['lifestyle tech', 'remote work', 'digital nomads'],
    localDetails: `Growing tech hub with lifestyle appeal. Strong remote work culture, health and wellness industry, tourism. Maroochydore CBD development attracting tech businesses.`,
  },
  {
    slug: 'townsville',
    name: 'Townsville',
    state: 'QLD',
    tier: 2,
    keywords: ['defence base', 'mining services', 'tropical agriculture'],
    localDetails: `Defence (Lavarack Barracks), mining services, James Cook University. Gateway to North Queensland mining and agriculture regions.`,
  },
  {
    slug: 'cairns',
    name: 'Cairns',
    state: 'QLD',
    tier: 2,
    keywords: ['tourism software', 'reef management', 'hospitality tech'],
    localDetails: `Tourism gateway to Great Barrier Reef, marine industries, tropical agriculture. Heavy reliance on booking systems and tourism management software.`,
  },
  {
    slug: 'darwin',
    name: 'Darwin',
    state: 'NT',
    tier: 2,
    keywords: ['resources sector', 'defence industry', 'remote operations'],
    localDetails: `Defence, resources, Asian trade gateway, government services. Remote location means finding local developers is challenging. Strong need for remote-friendly tools.`,
  },
]

export const tier1Cities = cities.filter((c) => c.tier === 1)
export const tier2Cities = cities.filter((c) => c.tier === 2)
