import type { Service } from './types'

export const services: Service[] = [
  {
    slug: 'mvp-development',
    name: 'MVP Development',
    description: 'Go from idea to working product in weeks. Validate before you invest everything.',
    priceRange: '$5-12K',
    timeline: '2-4 weeks',
    keyFeatures: [
      'Core features that prove your idea',
      'User auth & responsive design',
      'Deployed and ready for users',
      '1 week of post-launch support',
    ],
    typicalClient: 'Startup founder who needs to validate an idea before raising or spending more',
    keywords: ['MVP', 'minimum viable product', 'product launch', 'startup development'],
  },
  {
    slug: 'web-app-development',
    name: 'Web App Development',
    description: 'Custom web apps that replace spreadsheets, automate workflows, and actually get used.',
    priceRange: '$12-25K',
    timeline: '4-8 weeks',
    keyFeatures: [
      'Everything in MVP',
      'Integrations with your existing tools',
      'Admin dashboard & reporting',
      '2 weeks of post-launch support',
    ],
    typicalClient: 'Established business (5-50 staff) that has outgrown spreadsheets and generic tools',
    keywords: ['web application', 'custom web app', 'SaaS development', 'cloud application'],
  },
  {
    slug: 'custom-software-development',
    name: 'Custom Software Development',
    description: 'Bespoke software for complex business problems that off-the-shelf tools can\'t solve.',
    priceRange: '$15-40K',
    timeline: '6-12 weeks',
    keyFeatures: [
      'Custom architecture design',
      'Scalable infrastructure',
      'Ongoing support options',
      'Full documentation and handoff',
    ],
    typicalClient: 'Business with a specific problem that off-the-shelf tools can\'t solve',
    keywords: ['custom software', 'bespoke development', 'tailored solutions', 'enterprise software'],
  },
  {
    slug: 'internal-tools',
    name: 'Internal Tools',
    description: 'Dashboards, admin panels, and workflow tools your team will actually use.',
    priceRange: '$8-20K',
    timeline: '3-6 weeks',
    keyFeatures: [
      'Custom to your process',
      'Integrates with your existing stack',
      'Built for daily operations',
      'Training and documentation included',
    ],
    typicalClient: 'Operations manager or business owner tired of workarounds',
    keywords: ['internal tools', 'admin panels', 'back-office software', 'operational tools'],
  },
  {
    slug: 'startup-app-development',
    name: 'Startup App Development',
    description: 'End-to-end application development for startups, from concept through to launch and scale.',
    priceRange: '$10-30K',
    timeline: '4-10 weeks',
    keyFeatures: [
      'Full product strategy and build',
      'Scalable from day one',
      'User analytics and feedback loops',
      'Ongoing iteration support',
    ],
    typicalClient: 'Startup team that needs a technical partner to build and ship their product',
    keywords: ['startup app', 'product development', 'tech startup', 'app development'],
  },
  {
    slug: 'business-automation',
    name: 'Business Automation',
    description: 'Automate repetitive tasks and connect your tools so your team can focus on real work.',
    priceRange: '$5-15K',
    timeline: '2-4 weeks',
    keyFeatures: [
      'Workflow automation',
      'Tool integrations (Xero, Google, Slack, etc.)',
      'Custom dashboards',
      'Reduce manual data entry',
    ],
    typicalClient: 'Business owner who spends hours on repetitive admin tasks',
    keywords: ['automation', 'workflow automation', 'process automation', 'business efficiency'],
  },
]
